name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies with Bun
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: bun run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  dockerci:
    name: Docker CI
    needs: [build]
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Modify ENV
        run: |
          rm .env
          printf "PUBLIC_HOST_WISP=true\nPUBLIC_FILTER_OPTIMIZE=true\n" > .env

      - name: Build Docker image (timestamped)
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:$IMAGE_TAG

      - name: Build Docker image (latest)
        run: docker build . --file Dockerfile --tag ghcr.io/coding4hours/bromine:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "coding4Hours"
          password: ${{ secrets.TOKEN }}

      - name: Push Docker container (timestamped)
        run: docker push ghcr.io/coding4hours/bromine:$IMAGE_TAG

      - name: Push Docker container (latest)
        run: docker push ghcr.io/coding4hours/bromine:latest

  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    runs-on: ubuntu-slim
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

  changelog:
    name: Changelog
    runs-on: ubuntu-slim

    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}




